# Generated by Django 2.0.4 on 2018-04-11 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180410_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', related_query_name='track', to='website.Band'),
        ),
    ]
